# Generated by Django 6.0.3 on 2026-03-27 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='default', max_length=32, unique=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='default', max_length=32, unique=True)),
                ('nickname', models.CharField(max_length=120)),
                ('avatar_url', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectedDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('origin', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='UptimeMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=255)),
                ('check_type', models.CharField(choices=[('http', 'HTTP'), ('tcp', 'TCP')], default='http', max_length=16)),
                ('success_codes', models.CharField(blank=True, default='', max_length=255)),
                ('history', models.JSONField(blank=True, default=list)),
                ('latency_history', models.JSONField(blank=True, default=list)),
                ('checked_at_history', models.JSONField(blank=True, default=list)),
                ('last_status', models.IntegerField(blank=True, null=True)),
                ('last_latency', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WafLogEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('ip', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block')], max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=128)),
                ('method', models.CharField(blank=True, default='', max_length=16)),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('country', models.CharField(blank=True, default='', max_length=8)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WafSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='default', max_length=32, unique=True)),
                ('allowlist_enabled', models.BooleanField(default=True)),
                ('honeypot_enabled', models.BooleanField(default=True)),
                ('bot_ua_enabled', models.BooleanField(default=True)),
                ('header_inspection_enabled', models.BooleanField(default=True)),
                ('query_inspection_enabled', models.BooleanField(default=True)),
                ('body_inspection_enabled', models.BooleanField(default=True)),
                ('rate_limit_enabled', models.BooleanField(default=True)),
                ('adaptive_rate_limit_enabled', models.BooleanField(default=True)),
                ('spike_rate_limit_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllowlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('ip', 'IP'), ('ua', 'User Agent')], max_length=16)),
                ('value', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'ordering': ['entry_type', 'value'],
                'constraints': [models.UniqueConstraint(fields=('entry_type', 'value'), name='uniq_allowlist_entry')],
            },
        ),
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ip',), name='uniq_blacklist_ip')],
            },
        ),
        migrations.CreateModel(
            name='DenylistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('ua', 'User Agent'), ('country', 'Country')], max_length=16)),
                ('value', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'ordering': ['entry_type', 'value'],
                'constraints': [models.UniqueConstraint(fields=('entry_type', 'value'), name='uniq_denylist_entry')],
            },
        ),
    ]
